config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'pages/home'
  resources :machines
  # get "machines" => "restaurants#index"
  # get "machines/:id" => "restaurants#show"
  # get "machines/new" => "machines#new"
  # post "machines" => "machines#create"
  # get "machines/:id/edit" => "machines#edit"
  # patch "machines/:id" => "machines#update"
  # delete "machines/:id" => "machines#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/machine.rb
class Machine < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :set_machine, only: [:show, :edit, :update, :destroy]

  def index
    @machines = Machine.all
  end
  def show
  end
  def new
    @machine = Machine.new
  end
  def edit
  end
  def create
    machine = Machine.create(machine_params)
    redirect_to machines_path
  end
  def update
    redirect_to machines_path
  end
  def destroy
    @machine.destroy
    redirect_to machines_path
  end

  private

  def machine_params
    params.require(:machine).permit(:name, :brand)
  end

  def set_machine
    @machine = Machine.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/machines/edit.html.erb
<%= form_for @machine do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :brand %>
  <%= f.submit %>
<% end %>
<%= link_to "Retour sur liste du matériel", machines_path %>

app/views/machines/index.html.erb
<h1>Les Machines sont</h1>

<%= link_to "Ajouter une machine", new_machine_path %>

<% @machines.each do |machine| %>
  <h2> <%= machine.name %></h2>
  <h2> <%= machine.brand %></h2>
  <%= link_to "Voir", machine_path(machine) %>
  <%= link_to "Supprimer", machine_path(machine), method: :delete, data: {confirm: "Etes vous sur de vouloir supprimer l'élément ?" } %>

<% end %>

app/views/machines/new.html.erb
<%= form_for @machine do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :brand %>
  <%= f.submit %>
<% end %>
<%= link_to "Retour sur liste du matériel", machines_path %>

app/views/machines/show.html.erb
<h1><%= @machine.name %></h1>
  <h2> <%= @machine.brand %></h2>
<%= link_to "Retour sur liste du matériel", machines_path %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>